################################################################################
# simulation configs
################################################################################
sim_robot_variables:
  xml_filename: "/models/b2z1/b2z1_grasp.xml"
  use_fixed_base: False

  base_name: "base_link"
  joint_names: [
    "FL_hip_joint", "FL_thigh_joint", "FL_calf_joint", 
    "FR_hip_joint", "FR_thigh_joint", "FR_calf_joint", 
    "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint", 
    "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint", 
     "joint1", "joint2", "joint3", "joint4","joint5","joint6"
  ]  # pinocchio order
  limb_names: ["FL", "FR", "RL", "RR", "z1"]
  limb_endeff_names: ["FL_foot", "FR_foot", "RL_foot", "RR_foot", "link06"]

  base_init_pos: [0., 0., 0.80, 0., 0., 0., 1.] # posture
  base_init_vel: [0., 0., 0., 0., 0., 0.]
  joint_init_pos: [0., 0.75, -1.5, 
                   0., 0.75, -1.5, 
                   0., 0.75, -1.5, 
                   0., 0.75, -1.5,
                   0.,0.5,-1,0.3,0,0.]
  joint_init_vel: [0., 0., 0., 
                   0., 0., 0., 
                   0., 0., 0., 
                   0., 0., 0., 
                   0., 0., 0., 0., 0.,0.]


################################################################################
# control configs
################################################################################
control_variables:
  joint_names: [
    "FL_hip_joint", "FL_thigh_joint", "FL_calf_joint", 
    "FR_hip_joint", "FR_thigh_joint", "FR_calf_joint", 
    "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint", 
    "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint", 
    "joint1", "joint2", "joint3", "joint4","joint5","joint6"
  ]  # pinocchio order
  joint_des_pos: [0., 0.75, -1.5, 
                  0., 0.75, -1.5, 
                  0., 0.75, -1.5, 
                  0., 0.75, -1.5, 
                  0.,2.5,-1,-1.3,0,0.]
  joint_des_vel: [0., 0., 0., 
                  0., 0., 0., 
                  0., 0., 0., 
                  0., 0., 0., 
                  0., 0., 0., 0., 0.,0.0]

  joint_kp: [270., 270., 270., 
             270., 270., 270., 
             400., 400., 400., 
             400., 400., 400., 
             100., 100., 100., 100., 10., 10]
  joint_kd: [7., 7., 7., 
             7., 7., 7., 
             7., 7., 7., 
             7., 7., 7., 
             10., 10., 10., 5., 1.,1]